# Generated by Django 4.2.9 on 2026-07-25 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxis', '0002_taxi_active_driver_taxi_brand_taxi_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverRotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_type', models.CharField(choices=[('day', 'Day'), ('night', 'Night'), ('full', 'Full Day')], default='full', max_length=10)),
                ('days_of_week', models.JSONField(default=list, help_text='List of days (1-7 for Monday-Sunday)')),
                ('start_time', models.TimeField(help_text='Shift start time')),
                ('end_time', models.TimeField(help_text='Shift end time')),
                ('start_date', models.DateField(blank=True, help_text='Optional start date', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Optional end date', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotations', to=settings.AUTH_USER_MODEL)),
                ('taxi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotations', to='taxis.taxi')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('taxi', 'driver', 'shift_type', 'days_of_week', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='ShiftHandoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('outgoing_selfie', models.ImageField(blank=True, null=True, upload_to='handoffs/outgoing/')),
                ('incoming_selfie', models.ImageField(blank=True, null=True, upload_to='handoffs/incoming/')),
                ('biometric_verified', models.BooleanField(default=False)),
                ('biometric_match_confidence', models.FloatField(blank=True, null=True)),
                ('handoff_time', models.DateTimeField(blank=True, null=True)),
                ('handoff_location_lat', models.FloatField(blank=True, null=True)),
                ('handoff_location_lng', models.FloatField(blank=True, null=True)),
                ('odometer_reading', models.FloatField(blank=True, help_text='Odometer at handoff', null=True)),
                ('fuel_level', models.FloatField(blank=True, help_text='Fuel level percentage', null=True)),
                ('notes', models.TextField(blank=True, help_text='Any notes about the vehicle condition')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incoming_driver', models.ForeignKey(help_text='Driver starting shift', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_handoffs', to=settings.AUTH_USER_MODEL)),
                ('outgoing_driver', models.ForeignKey(help_text='Driver ending shift', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_handoffs', to=settings.AUTH_USER_MODEL)),
                ('taxi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handoffs', to='taxis.taxi')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverShiftHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_start', models.DateTimeField()),
                ('shift_end', models.DateTimeField(blank=True, null=True)),
                ('total_distance', models.FloatField(default=0, help_text='Distance traveled in km')),
                ('total_trips', models.IntegerField(default=0, help_text='Number of trips completed')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, help_text='Revenue earned', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Is shift currently active')),
                ('ended_cleanly', models.BooleanField(default=True, help_text='Did shift end normally')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_history', to=settings.AUTH_USER_MODEL)),
                ('rotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rotations.driverrotation')),
                ('taxi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_histories', to='taxis.taxi')),
            ],
            options={
                'ordering': ['-shift_start'],
            },
        ),
    ]
