# Generated by Django 4.2.9 on 2026-07-27 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_driverprofile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='plate_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
