# Generated by Django 4.2.9 on 2026-07-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_driverprofile_plate_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='license_photo',
            field=models.ImageField(blank=True, null=True, upload_to='driver_licenses/'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='vehicle_photo',
            field=models.ImageField(blank=True, null=True, upload_to='driver_vehicles/'),
        ),
    ]
