# Generated by Django 4.2.9 on 2026-07-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_driverprofile_license_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='cni_photo',
            field=models.ImageField(blank=True, null=True, upload_to='driver_cni/'),
        ),
    ]
