# Generated by Django 4.2.9 on 2026-08-15 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_driverprofile_birth_date_driverprofile_cni_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='qr_code',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
