# Generated by Django 4.2.9 on 2026-08-16 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_driverprofile_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='face_embedding',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='driver_profiles/'),
        ),
    ]
