# Generated by Django 4.2.9 on 2026-09-22 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_emergencycontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontact',
            name='relation',
            field=models.CharField(choices=[('parent', 'Parent'), ('sibling', 'Frere/Soeur'), ('spouse', 'Conjoint(e)'), ('child', 'Enfant'), ('friend', 'Ami(e)'), ('colleague', 'Collegue'), ('other', 'Autre')], default='other', max_length=20),
        ),
    ]
