# Generated by Django 4.2.9 on 2026-09-28 18:29

from django.db import migrations
from django.contrib.auth.hashers import make_password


def create_admin_user(apps, schema_editor):
    CustomUser = apps.get_model('users', 'CustomUser')
    if not CustomUser.objects.filter(username='admin').exists():
        admin = CustomUser.objects.create_superuser(
            username='admin',
            email='admin@safetaxi.cm',
            password='AdminPass123!',
            role='admin'
        )
        admin.is_staff = True
        admin.is_superuser = True
        admin.save()
        print("Admin user created: admin / AdminPass123!")


def reverse_admin_user(apps, schema_editor):
    CustomUser = apps.get_model('users', 'CustomUser')
    CustomUser.objects.filter(username='admin').delete()
    print("Admin user deleted")


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_emergencycontact_relation'),
    ]

    operations = [
        migrations.RunPython(create_admin_user, reverse_admin_user),
    ]
