# Generated by Django 4.2.9 on 2026-07-07 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=64)),
                ('model', models.CharField(blank=True, max_length=128)),
                ('capacity', models.IntegerField(default=4)),
                ('is_active', models.BooleanField(default=True)),
                ('last_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('last_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_taxis', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
