# Generated by Django 4.2.9 on 2026-07-13 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxi',
            name='active_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_taxi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxi',
            name='brand',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='taxi',
            name='color',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='taxi',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='taxi',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='taxi_images/'),
        ),
        migrations.AddField(
            model_name='taxi',
            name='qr_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='taxi',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
