# Generated by Django 4.2.9 on 2026-08-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxis', '0002_taxi_active_driver_taxi_brand_taxi_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxi',
            name='license_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
