# Generated by Django 4.2.9 on 2026-09-22 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trips', '0003_deposit'),
        ('sos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='accuracy',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='alert_type',
            field=models.CharField(blank=True, choices=[('aggression', 'Aggression'), ('accident', 'Accident'), ('medical', 'Medical'), ('kidnapping', 'Kidnapping'), ('robbery', 'Robbery'), ('harassment', 'Harassment'), ('other', 'Other')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='trips.trip'),
        ),
    ]
