# Generated by Django 4.2.9 on 2026-10-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('offered', 'Offered'), ('validated', 'Validated'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='trip',
            name='join_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
