# Generated by Django 4.2.9 on 2026-10-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_alter_deposit_status_alter_trip_join_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='join_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
