# Generated by Django 4.2.9 on 2026-10-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_auto_20261007_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='start_lat',
            field=models.DecimalField(decimal_places=6, max_digits=12, null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_lng',
            field=models.DecimalField(decimal_places=6, max_digits=12, null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='current_lat',
            field=models.DecimalField(decimal_places=6, max_digits=12, null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='current_lng',
            field=models.DecimalField(decimal_places=6, max_digits=12, null=True, blank=True),
        ),
    ]
