# Generated by Django 4.2.9 on 2026-10-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_auto_20261007_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='dropoff_lat',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='dropoff_lng',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='pickup_lat',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='pickup_lng',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
    ]
