# Generated by Django 4.2.9 on 2026-07-07 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selfie', models.FileField(upload_to='biometric/selfies/')),
                ('reference', models.FileField(blank=True, null=True, upload_to='biometric/references/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('verified', 'Verified'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
